name: AIO Params
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on:
  workflow_dispatch:
    inputs:
      Cycle_Key:
        type: string
        description: 'Enter cycle Key'
        required: false
      Project_key:
        type: string
        description: 'Enter project key?'
        default: false
      Case_key_list:
        type: string
        description: 'Case key list'
        required: false
        default: '1.0.0'
      case_auto_key_list:
        type: string
        description: 'case auto key list'
      AIO_API_Token:
        type: string
        description: 'AIO API Token'
        required: false
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Echo provided inputs
        run: |
          echo "ğŸŒ Environment: ${{ github.event.inputs.environment }}"
          echo "âœ… Confirm Deploy: ${{ github.event.inputs.confirm_deploy }}"
          echo "ğŸ“¦ Release Version: ${{ github.event.inputs.release_version }}"
          echo "ğŸ“¦ Current Version: ${{ github.event.inputs.current_version }}"
          echo "ğŸ“¡ Deployment Region: ${{ github.event.inputs.deployment_region }}"
      - run: echo "ğŸ This job's status is ${{ job.status }}."
